Repository handsontable/handsontable, pull requests merged in 2018-11, with the labels that each got.

#5183 Add lv-LV Latvian-Latvia translation
  src/i18n/languages/index.js
  src/i18n/languages/lv-LV.js
Labels: CLA signed, Help needed, Translation

#5355 Korean langauge support
  src/i18n/languages/index.js
  src/i18n/languages/ko-KR.js
Labels: CLA signed, Help needed, Translation

#5307 Fix selection and context menu type annotations
  handsontable.d.ts
Labels: CLA signed, Status: Developed (ready for review)

#5412 [FIX] Issue-4162
  src/renderers/checkboxRenderer.js
  test/e2e/renderers/checkboxRenderer.spec.js
Labels: CLA signed, Status: Developed (ready for review)

#5537 Remove extra \r in pasted data
  lib/SheetClip/SheetClip.js
Labels: CLA signed, Status: Developed (ready for review)

#4710 Issue #4400 Fixed ObserveChanges plugin memory leak
  lib/jsonpatch/json-patch-duplex.js
Labels: CLA signed, Plugin: observe changes, Status: Developed (ready for review)

#5294 Fix table cell highlight bug when scrolling the table on mobile device
  src/3rdparty/walkontable/src/event.js
Labels: CLA signed

#5451 Convert SelectEditor to ES6
  src/editors/selectEditor.js
Labels: CLA signed, Status: Developed (ready for review)

#5452 Convert HandsontableEditor to ES6 class
  src/editors/handsontableEditor.js
Labels: CLA signed, Status: Developed (ready for review)

#5580 Rewrite loop that removes many individual mapped row indices to run faster
  src/mixins/arrayMapper.js
  test/unit/mixins/arrayMapper.spec.js
Labels: CLA signed, Status: Developed (ready for review)

#5447 Convert BaseEditor to use ES6 class and arrow function scope
  src/editors/_baseEditor.js
Labels: CLA signed, Status: Developed (ready for review)
