Repository handsontable/handsontable, pull requests merged in 2018-03, with the labels that each got.

#4543 add support to beforeValueRender hook for parameters "TD, row, col, prop, value, cellProperties
  handsontable.d.ts
  src/tableView.js
  test/e2e/Core_render.spec.js
  test/types/handsontable-tests.ts
Labels: Status: Developed (ready for review)

#4853 Added Russian translations (#4696)
  README.md
  src/i18n/languages/index.js
  src/i18n/languages/ru-RU.js
Labels: Status: Developed (ready for review), Translation

#4918 Update handsontable.d.ts
  handsontable.d.ts
Labels: Status: Developed (ready for review), TypeScript

#4983 Issue template class name change
  .github/ISSUE_TEMPLATE.md
Labels: Type: Bug
