Repository handsontable/handsontable, pull requests merged in 2018-05, with the labels that each got.

#4898 Add es-MX language support
  src/i18n/languages/es-MX.js
  src/i18n/languages/index.js
Labels: Status: Developed (ready for review), Translation

#4685 Translations for Norwegian Bokmål
  src/i18n/languages/nb-NO.js
Labels: Status: Developed (ready for review), Translation

#5106 Missing change for Norwegian Bokmål translation
  src/i18n/languages/index.js
Labels: Status: Developed (ready for review)

#4979 Fix afterSelectionEnd not being fired correctly on mobile
  src/tableView.js
  test/unit/EventManager.spec.js
Labels: CLA signed, Status: Developed (ready for review)

#5109 Overloaded definitions for setDataAtCell and setDataAtRowProp
  handsontable.d.ts
  test/types/methods.types.ts
Labels: CLA signed, Status: Developed (ready for review)

#4574 Fix: fix getSourceDataAtCol always get undefined issue
  src/dataSource.js
  test/e2e/core/getSourceDataAtCol.spec.js
Labels: CLA signed, Status: Developed (ready for review), Status: To be discussed
