Repository handsontable/handsontable, pull requests merged in 2018-10, with the labels that each got.

#5155 nl_NL language support.
  src/i18n/languages/index.js
  src/i18n/languages/nl-NL.js
Labels: CLA signed, Help needed, Translation

#5406 Add it-IT language
  src/i18n/languages/index.js
  src/i18n/languages/it-IT.js
Labels: CLA signed, Translation

#5425 Fix typings for beforeColumnMove and beforeRowMove (#5416)
  handsontable.d.ts
Labels: CLA signed, Status: Developed (ready for review), TypeScript
