Repository handsontable/handsontable, pull requests merged in 2019-07, with the labels that each got.

#6077 Fix tests failing in the browser and other test improvements.
  package-lock.json
  package.json
  src/3rdparty/walkontable/test/spec/settings/stretchH.spec.js
  src/editors/dateEditor.js
  src/editors/handsontableEditor.js
  src/plugins/autoColumnSize/test/autoColumnSize.e2e.js
  src/plugins/autoRowSize/test/autoRowSize.e2e.js
  src/plugins/comments/commentEditor.js
  src/plugins/contextMenu/menu.js
  src/plugins/contextMenu/test/contextMenu.e2e.js
  src/plugins/formulas/test/formula/math-trig.e2e.js
  src/plugins/hiddenColumns/test/hiddenColumns.e2e.js
  src/validators/dateValidator.js
  test/e2e/Core_destroy.spec.js
  test/e2e/Core_init.spec.js
  test/e2e/Core_reCreate.spec.js
  test/e2e/Core_validate.spec.js
  test/e2e/Core_view.spec.js
  test/e2e/Dom.spec.js
  test/e2e/MemoryLeakTest.js
  test/e2e/editors/dateEditor.spec.js
  test/e2e/editors/textEditor.spec.js
  test/e2e/settings/fragmentSelection.spec.js
  test/e2e/validators/dateValidator.spec.js
  yarn.lock
Labels: Status: Developed (ready for review), Type: Improvement suggestion

#6122 Fix a problem, where it was impossible to open the filter dropdown ...
  src/plugins/contextMenu/menu.js
  src/plugins/filters/test/filtersUI.e2e.js
Labels: Dropdown menu, Filtering, Type: Bug

#6127 Add 'getCommentAtCell' method into typings
  handsontable.d.ts
Labels: CLA signed, Status: Developed (ready for review)

#6161 Remove yarn.lock from repository
  .travis.yml
  yarn.lock
Labels: Status: Developed (ready for review), Type: Change
