Repository handsontable/handsontable, pull requests merged in 2021-12, with the labels that each got.

#8952 Docs: Expanding the 10->11 migration guide with TypeScript info
  docs/11.0/guides/upgrade-and-migration/migrating-from-10.0-to-11.0.md
  docs/next/guides/upgrade-and-migration/migrating-from-10.0-to-11.0.md
Labels: documentation

#9000 Fix Typescript return type in React wrapper
  .changelogs/9000.json
  wrappers/react/src/types.tsx
Labels: Status: Developed (ready for review), CLA signed

#9004 Docs: Adding HyperFormula version support section
  docs/10.0/guides/formulas/formula-calculation.md
  docs/11.0/guides/formulas/formula-calculation.md
  docs/9.0/guides/formulas/formula-calculation.md
  docs/next/guides/formulas/formula-calculation.md
Labels: documentation

#9017 Docs: Updating the Snyk badge
  README.md
  handsontable/README.md
Labels: documentation

#8986 Docs: Migrating remaining CodeSandbox examples
  docs/.vuepress/handsontable-manager/dependencies.js
  docs/.vuepress/public/scripts/fixer.js
  docs/10.0/guides/integrate-with-react/react-hot-column.md
  docs/10.0/guides/integrate-with-vue/vue-hot-column.md
  docs/11.0/guides/integrate-with-vue/vue-hot-column.md
  docs/9.0/guides/integrate-with-react/react-hot-column.md
  docs/9.0/guides/integrate-with-vue/vue-hot-column.md
  docs/next/guides/integrate-with-vue/vue-hot-column.md
Labels: documentation

#9038 Docs: Removing Codeship badges from wrapper READMEs
  wrappers/angular/README.md
  wrappers/react/README.md
  wrappers/vue/README.md
  wrappers/vue3/README.md
Labels: documentation

#8985 Docs: Changing the 'Breaking change' format
  CHANGELOG.md
  bin/changelog
  docs/10.0/guides/upgrade-and-migration/release-notes.md
  docs/11.0/guides/upgrade-and-migration/release-notes.md
  docs/9.0/guides/upgrade-and-migration/release-notes.md
  docs/next/guides/upgrade-and-migration/release-notes.md
Labels: documentation

#9041 Docs: Adding render() to code samples
  docs/10.0/guides/columns/column-hiding.md
  docs/11.0/guides/columns/column-hiding.md
  docs/next/guides/columns/column-hiding.md
Labels: documentation

#9020 Docs: Updating Vue 3 readme
  CONTRIBUTING.md
  README.md
  docs/10.0/api/columnSorting.md
  docs/11.0/api/columnSorting.md
  docs/9.0/api/columnSorting.md
  handsontable/README.md
  handsontable/dist/README.md
  wrappers/angular/README.md
  wrappers/react/README.md
  wrappers/vue/README.md
  wrappers/vue3/README.md
  wrappers/vue3/package.json
Labels: documentation

#9056 Docs: Editing the CONTRIBUTING.md file
  CONTRIBUTING.md
Labels: documentation

#8928 [RTL] Fixed an issue with context menu in RTL mode.
  .changelogs/8825.json
  .changelogs/8828.json
  .eslintrc.js
  docs/.vuepress/tools/jsdoc-convert/renderer/preProcessors/removeInternals.mjs
  docs/.vuepress/tools/jsdoc-convert/renderer/renderer.mjs
  handsontable/src/css/handsontable.scss
  handsontable/src/plugins/base/base.js
  handsontable/src/plugins/contextMenu/__tests__/contextMenu.spec.js
  handsontable/src/plugins/contextMenu/__tests__/positioning.spec.js
  handsontable/src/plugins/contextMenu/__tests__/rtl/positioning.spec.js
  handsontable/src/plugins/contextMenu/contextMenu.js
  handsontable/src/plugins/contextMenu/contextMenu.scss
  handsontable/src/plugins/contextMenu/menu.js
  handsontable/src/plugins/dropdownMenu/__tests__/positioning.spec.js
  handsontable/src/plugins/dropdownMenu/__tests__/rtl/positioning.spec.js
  handsontable/src/plugins/dropdownMenu/dropdownMenu.js
  handsontable/src/plugins/dropdownMenu/dropdownMenu.scss
  handsontable/src/plugins/filters/filters.scss
  handsontable/src/plugins/filters/ui/select.js
  handsontable/test/helpers/common.js
Labels: Context menu, RTL

#9060 Docs: Changing the cookiebot buttons' colors in dark theme
  docs/.vuepress/theme/styles/cookiebot.styl
  docs/.vuepress/theme/styles/index.styl
Labels: documentation

#8891 Docs: adding info on the accordion markdown container
  docs/README-EDITING.md
Labels: documentation

#9043 Add ability to create custom redirects for documentation.
  docs/.gitignore
  docs/.vuepress/config.js
  docs/.vuepress/plugins/generate-nginx-redirects/index.js
  docs/README.md
  docs/docker/Dockerfile
  docs/docker/default.conf
  docs/docker/redirects.conf
Labels: documentation
