Repository handsontable/handsontable, pull requests merged in 2021-11, with the labels that each got.

#8854 Add modularization support for React wrapper
  .changelogs/8819.json
  wrappers/react/.config/base.js
  wrappers/react/.config/minified.js
  wrappers/react/.config/umd.js
  wrappers/react/package.json
  wrappers/react/src/baseEditorComponent.tsx
  wrappers/react/src/hotColumn.tsx
  wrappers/react/src/hotTable.tsx
  wrappers/react/src/settingsMapper.ts
  wrappers/react/src/types.tsx
  wrappers/react/test/_helpers.tsx
  wrappers/react/test/autoSizeWarning.spec.tsx
  wrappers/react/test/componentInternals.spec.tsx
  wrappers/react/test/hotColumn.spec.tsx
  wrappers/react/test/hotTable.spec.tsx
  wrappers/react/test/reactContext.spec.tsx
  wrappers/react/test/reactHooks.spec.tsx
  wrappers/react/test/reactLazy.spec.tsx
  wrappers/react/test/reactMemo.spec.tsx
  wrappers/react/test/reactPureComponent.spec.tsx
  wrappers/react/test/redux.spec.tsx
Labels: Breaking change

#8861 Add modularization support for Vue wrapper
  .changelogs/8820.json
  wrappers/vue/.config/base.js
  wrappers/vue/.config/minified.js
  wrappers/vue/.config/umd.js
  wrappers/vue/src/BaseEditorComponent.vue
  wrappers/vue/src/HotTable.vue
  wrappers/vue/src/helpers.ts
  wrappers/vue/src/types.ts
  wrappers/vue/test/baseEditorComponent.spec.ts
  wrappers/vue/test/hotColumn.spec.ts
  wrappers/vue/test/hotTable.spec.ts
  wrappers/vue/test/nestedRows.spec.ts
Labels: Breaking change

#8862 Add modularization support for Angular wrapper
  .changelogs/8818.json
  wrappers/angular/projects/hot-table/ng-package.json
  wrappers/angular/projects/hot-table/src/lib/helpers.ts
  wrappers/angular/projects/hot-table/src/lib/hot-column.component.spec.ts
  wrappers/angular/projects/hot-table/src/lib/hot-column.component.ts
  wrappers/angular/projects/hot-table/src/lib/hot-settings-resolver.service.ts
  wrappers/angular/projects/hot-table/src/lib/hot-table-registerer.service.spec.ts
  wrappers/angular/projects/hot-table/src/lib/hot-table-registerer.service.ts
  wrappers/angular/projects/hot-table/src/lib/hot-table.component.spec.ts
  wrappers/angular/projects/hot-table/src/lib/hot-table.component.ts
Labels: Breaking change

#8924 Docs: Changes related to #6095
  .changelogs/6095.json
  .changelogs/8897.json
  docs/10.0/guides/building-and-testing/modules.md
  docs/10.0/guides/integrate-with-angular/angular-setting-up-a-locale.md
  docs/10.0/guides/integrate-with-react/react-setting-up-a-locale.md
  docs/10.0/guides/integrate-with-vue/vue-setting-up-a-locale.md
  docs/9.0/guides/building-and-testing/modules.md
  docs/next/guides/building-and-testing/modules.md
  docs/next/guides/integrate-with-angular/angular-setting-up-a-locale.md
  docs/next/guides/integrate-with-react/react-setting-up-a-locale.md
  docs/next/guides/integrate-with-vue/vue-setting-up-a-locale.md
  docs/next/guides/internationalization/internationalization-i18n.md
  handsontable/src/dataMap/metaManager/metaSchema.js
Labels: documentation

#8925 Docs: Changing filenames and links
  docs/next/guides/integrate-with-angular/angular-setting-up-a-language.md
  docs/next/guides/integrate-with-react/react-setting-up-a-language.md
  docs/next/guides/integrate-with-vue/vue-setting-up-a-language.md
  docs/next/guides/sidebar.js
Labels: documentation

#8892 Docs: adding wrapper modularization docs
  docs/next/guides/building-and-testing/modules.md
  docs/next/guides/integrate-with-angular/angular-custom-context-menu-example.md
  docs/next/guides/integrate-with-angular/angular-custom-editor-example.md
  docs/next/guides/integrate-with-angular/angular-custom-id.md
  docs/next/guides/integrate-with-angular/angular-custom-renderer-example.md
  docs/next/guides/integrate-with-angular/angular-hot-reference.md
  docs/next/guides/integrate-with-angular/angular-installation.md
  docs/next/guides/integrate-with-angular/angular-language-change-example.md
  docs/next/guides/integrate-with-angular/angular-modules.md
  docs/next/guides/integrate-with-angular/angular-setting-up-a-language.md
  docs/next/guides/integrate-with-angular/angular-simple-example.md
  docs/next/guides/integrate-with-react/react-custom-context-menu-example.md
  docs/next/guides/integrate-with-react/react-custom-editor-example.md
  docs/next/guides/integrate-with-react/react-custom-renderer-example.md
  docs/next/guides/integrate-with-react/react-hot-reference.md
  docs/next/guides/integrate-with-react/react-installation.md
  docs/next/guides/integrate-with-react/react-language-change-example.md
  docs/next/guides/integrate-with-react/react-modules.md
  docs/next/guides/integrate-with-react/react-redux-example.md
  docs/next/guides/integrate-with-react/react-setting-up-a-language.md
  docs/next/guides/integrate-with-react/react-simple-example.md
  docs/next/guides/integrate-with-vue/vue-custom-context-menu-example.md
  docs/next/guides/integrate-with-vue/vue-custom-editor-example.md
  docs/next/guides/integrate-with-vue/vue-custom-id-class-style.md
  docs/next/guides/integrate-with-vue/vue-custom-renderer-example.md
  docs/next/guides/integrate-with-vue/vue-hot-column.md
  docs/next/guides/integrate-with-vue/vue-hot-reference.md
  docs/next/guides/integrate-with-vue/vue-installation.md
  docs/next/guides/integrate-with-vue/vue-language-change-example.md
  docs/next/guides/integrate-with-vue/vue-modules.md
  docs/next/guides/integrate-with-vue/vue-setting-up-a-language.md
  docs/next/guides/integrate-with-vue/vue-simple-example.md
  docs/next/guides/integrate-with-vue/vue-vuex-example.md
  docs/next/guides/sidebar.js
Labels: documentation

#8914 Docs: Adding info on the `autoRowSize` option impacting the scrollbar size
  handsontable/src/dataMap/metaManager/metaSchema.js
  handsontable/src/plugins/autoRowSize/autoRowSize.js
Labels: documentation

#8913 Docs: Unifying standalone link styling
  docs/next/guides/cell-features/clipboard.md
  docs/next/guides/formulas/formula-calculation.md
  docs/next/guides/getting-started/events-and-hooks.md
  docs/next/guides/getting-started/hello-world.md
  docs/next/guides/getting-started/installation.md
  docs/next/guides/getting-started/introduction.md
  docs/next/guides/getting-started/saving-data.md
  docs/next/guides/rows/row-sorting.md
  handsontable/src/dataMap/metaManager/metaSchema.js
Labels: documentation

#8884 Docs: Updating docs due to project structure change
  CONTRIBUTING.md
  docs/README.md
  docs/next/guides/building-and-testing/building.md
  docs/next/guides/building-and-testing/file-structure.md
  docs/next/guides/building-and-testing/testing.md
Labels: documentation

#8889 [RTL] Styling fixations for the table
  .changelogs/8767.json
  handsontable/.config/test-walkontable.js
  handsontable/.config/walkontable.js
  handsontable/package.json
  handsontable/src/3rdparty/walkontable/css/walkontable.scss
  handsontable/src/3rdparty/walkontable/src/overlay/top.js
  handsontable/src/base.js
Labels: RTL

#8931 Docs: Adding HoT 11 docs
  CHANGELOG.md
  docs/11.0/guides/building-and-testing/file-structure.md
  docs/11.0/guides/sidebar.js
  docs/11.0/guides/upgrade-and-migration/migrating-from-10.0-to-11.0.md
  docs/11.0/guides/upgrade-and-migration/release-notes.md
  docs/next/guides/building-and-testing/file-structure.md
  docs/next/guides/sidebar.js
  docs/next/guides/upgrade-and-migration/migrating-from-10.0-to-11.0.md
  docs/next/guides/upgrade-and-migration/release-notes.md
Labels: documentation

#8893 [RTL] Fixes for cell types
  .changelogs/8795.json
  .changelogs/8797.json
  .changelogs/8802.json
  handsontable/src/editors/autocompleteEditor/__tests__/autocompleteEditor.spec.js
  handsontable/src/editors/autocompleteEditor/autocompleteEditor.js
  handsontable/src/plugins/filters/filters.js
  handsontable/src/plugins/filters/filters.scss
  handsontable/src/renderers/autocompleteRenderer/autocompleteRenderer.js
  handsontable/src/renderers/autocompleteRenderer/autocompleteRenderer.scss
Labels: RTL

#8962 Docs: Moving the React "Using the HotColumn component" examples from CodeSandbox to the HoT docs
  docs/11.0/guides/integrate-with-react/react-hot-column.md
  docs/next/guides/integrate-with-react/react-hot-column.md
Labels: documentation

#8975 Docs: Adding a broken links procedure to docs' readme
  docs/README-EDITING.md
  docs/README.md
Labels: documentation

#8966 Docs: Moving the React "Using the HotColumn component" examples from CodeSandbox to the HoT docs
  docs/.vuepress/handsontable-manager/dependencies.js
  docs/.vuepress/public/scripts/fixer.js
  docs/11.0/guides/integrate-with-react/react-hot-column.md
  docs/README-EDITING.md
  docs/next/guides/integrate-with-react/react-hot-column.md
Labels: documentation

#8959 Docs: Updating the Options API ref
  handsontable/src/dataMap/metaManager/metaSchema.js
Labels: documentation

#8988 Docs: Hiding the Hello World page
  docs/10.0/api/introduction.md
  docs/10.0/guides/getting-started/introduction.md
  docs/10.0/guides/sidebar.js
  docs/11.0/api/introduction.md
  docs/11.0/guides/getting-started/introduction.md
  docs/11.0/guides/sidebar.js
  docs/9.0/api/introduction.md
  docs/9.0/guides/getting-started/introduction.md
  docs/9.0/guides/sidebar.js
Labels: documentation
