Repository handsontable/handsontable, pull requests merged in 2025-03, with the labels that each got.

#11467 Add null checks for getCoords
  handsontable/src/3rdparty/walkontable/src/table.js
Labels: CLA signed

#11502 Fix a problem with a delayed `scroll` event making some of the test cases fail randomly.
  handsontable/src/core/viewportScroll/__tests__/columnHeaderSelection.spec.js
  handsontable/src/core/viewportScroll/__tests__/cornerHeaderSelection.spec.js
  handsontable/src/core/viewportScroll/__tests__/generalHorizontalScroll.spec.js
  handsontable/src/core/viewportScroll/__tests__/generalVerticalScroll.spec.js
  handsontable/src/core/viewportScroll/__tests__/multipleSelection.spec.js
  handsontable/src/core/viewportScroll/__tests__/noncontiguousSelection.spec.js
  handsontable/src/core/viewportScroll/__tests__/rowHeaderSelection.spec.js
  handsontable/src/core/viewportScroll/__tests__/rtl/columnHeaderSelection.spec.js
  handsontable/src/core/viewportScroll/__tests__/rtl/multipleSelection.spec.js
  handsontable/src/core/viewportScroll/__tests__/rtl/noncontiguousSelection.spec.js
  handsontable/src/core/viewportScroll/__tests__/rtl/singleSelection.spec.js
  handsontable/src/core/viewportScroll/__tests__/singleSelection.spec.js
  handsontable/src/plugins/comments/__tests__/comments.spec.js
  handsontable/src/plugins/dragToScroll/__tests__/dragToScroll.spec.js
  handsontable/src/plugins/manualColumnMove/__tests__/scrolling.spec.js
  handsontable/test/helpers/common.js
Labels: Tests: E2E, Tools

#11366 Fixing issue with NestedRows plugin duplicating rows when moving children
  .changelogs/11362.json
  handsontable/src/plugins/nestedRows/__tests__/nestedRows.spec.js
  handsontable/src/plugins/nestedRows/data/dataManager.js
Labels: Status: Developed (ready for review), CLA signed
